# Generated by Django 2.2.1 on 2019-05-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upvote',
            field=models.ManyToManyField(default=None, related_name='_product_upvote_+', to='products.Product'),
        ),
    ]
