# Generated by Django 2.2.1 on 2019-05-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_upvotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='upvotes',
            new_name='upvote',
        ),
    ]
